### ISSUE TITLE
Upgrade to elasticsearch 8.

### ISSUE THREAD

**Issue by mcollina** [fastify/fastify-elasticsearch#78]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

ElasticSearch 8 now requires https for every communication. This makes the current approach we use for running tests moot.

We need some new setup and I do not have time to look into it right now.

@delvedor can you help?

**Comment by delvedor** [comment]
> ElasticSearch 8 now requires https for every communication.

This isn't entirely true, it requires https by default, but it can be disabled with `--env "xpack.security.enabled=false"`.

Otherwise, we can migrate to [elastic/elastic-github-actions](https://github.com/elastic/elastic-github-actions), which [has been updated](https://github.com/elastic/elastic-github-actions/pull/25) to better support security on by default.
While testing the code should either avoid rejecting unauthorized certs, or set `security-enabled: false` in the action settings.
